export const IMAGES = {
  logo: require('../../assets/images/D.png'),
  box: require('../../assets/images/box.png'),
  background: require('../../assets/images/BG.png'),
  tab: require('../../assets/images/Tab.png'),
  shoppingCart: require('../../assets/images/shopping-cart.png'),
  shoppingCartCol: require('../../assets/images/shopping-cartCol.png'),
  user: require('../../assets/images/user.png'),
  tabCol: require('../../assets/images/tabCol.png'),
  arrow: require('../../assets/images/Vector.png'),
  search: require('../../assets/images/search.png'),
  item1: require('../../assets/images/item1.png'),
  item2: require('../../assets/images/item2.png'),
  item3: require('../../assets/images/item3.png'),
  item4: require('../../assets/images/item4.png'),
  item5: require('../../assets/images/item5.png'),
  item6: require('../../assets/images/item6.png'),
  tick: require('../../assets/images/Tick.png'),
  veg: require('../../assets/images/veg.png'),
  veg2: require('../../assets/images/veg2.png'),
  veg3: require('../../assets/images/veg3.png'),
  wish: require('../../assets/images/wish.png'),
  wishclr: require('../../assets/images/wishclr.png'),
  cart: require('../../assets/images/cart.png'),
  bgImage: require('../../assets/images/bgimage.png'),
};

export const FONTS = {
  robotoRegular: 'Roboto-Regular',
  robotoBold: 'Roboto-Bold',
  sfRegular: 'SF-Pro-Text-Regular',
};

export const COLORS = {
  background: '#A259FF',
  grey: '#F6F5F5',
  button: '#0BCE83',
  white: '#FFFFFF',
  heading: '#2D0C57',
  para: '#9586A8',
  logoBG: '#CDFFB6',
  border: '#D9D0E3',
  list: '#E2CBFF',
  darkPurple: '#6C0EE4',
};
